name: deepchem
channels:
- rdkit
- defaults
dependencies:
- bzip2=1.0.6=3
- cairo=1.14.8=0
- certifi=2016.2.28=py35_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- jbig=2.1=0
- jpeg=9b=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- mkl=2017.0.3=0
- numpy=1.11.3=py35_0
- olefile=0.44=py35_0
- openssl=1.0.2l=0
- pandas=0.20.1=np111py35_0
- pillow=4.2.1=py35_0
- pip=9.0.1=py35_1
- pixman=0.34.0=0
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- readline=6.2=2
- setuptools=36.4.0=py35_1
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- boost=1.56.0=py35_3
- ncurses=6.0=0
- postgresql=9.4.4=py35_0
- rdkit=2016.03.4=np111py35_1
- rdkit-postgresql=2016.03.4=py35_1
- pip:
  - algopy==0.5.7
  - biopython==1.71
  - cycler==0.10.0
  - kiwisolver==1.0.1
  - matplotlib==2.2.2
  - numdifftools==0.9.20
  - patsy==0.5.0
  - pyparsing==2.2.0
  - scikit-learn==0.19.1
  - scipy==1.0.1
  - sklearn==0.0
  - statsmodels==0.8.0
  - xgboost==0.7.post4

